--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/Treequel
project_requirements: 
  ldap: ">=0"
release_smtphost: mail.faeriemud.org
project_description: |-
  A library for interacting with LDAP (modeled after Sequel). It is an attempt to remove
  the impedence mismatch of trying to treat LDAP as if it's a relational database, and
  instead embrace its hierarchical, free-form nature.
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: 
  ruby-ldap: ">= 0.9.9"
project_summary: An honest LDAP library
version_file: treequel.rb
additional_pkgfiles: 
- examples/**/*.{rb,erb,css,png}
dev_dependencies: 
  columnize: ">= 0.3.1"
  termios: ">= 0.9.4"
  diff-lcs: ">= 1.1.2"
  ruby-terminfo: ">= 0.1.1"
authors: 
  Mahlon E. Smith: mahlon@martini.nu
  Michael Granger: ged@FaerieMUD.org
post_install_message: |-
  If you want to use the included 'treequel' LDAP shell, you'll need to install
  the following libraries as well:
      - termios
      - ruby-terminfo
      - columnize
      - diff-lcs
project_name: Treequel
